### ISSUE TITLE
Error in test.js

### ISSUE THREAD

**Issue by jhiemer** [openservicebrokerapi/osb-checker#33] opened 2018-04-24 20:36 UTC
Hi, 
please excuse, the perhaps stupid question, but isn't that wrong: 

https://github.com/openservicebrokerapi/osb-checker/blob/master/2.13/tests/test/test.js#L379

Why is this below bindings and not in provisions?

**Comment by leonwanghui** [comment] 2018-07-24 01:36
@jhiemer I think it should be bindings, and the url is not right then.

**Comment by leonwanghui** [comment] 2018-07-30 00:53
Hi @duglin @mattmcneeney , please assign it to me if nobody is willing to solve this problem, thanks!

**Comment by mattmcneeney** [comment] 2018-07-30 08:36
Those tests seem to be related to deprovisioning. Sorry if this is a stupid question, but I'm not sure what the problem is here?

**Comment by leonwanghui** [comment] 2018-07-30 08:51
Hi @mattmcneeney , IMO technically it works fine, but what confuses people is why we pass some configuration data of binding into deprovision test case. What do you think?

**Comment by mattmcneeney** [comment] 2018-07-30 08:59
Ah I see, thanks. Yeah that is strange - especially because it's not even testing anything to do with bindings (it's not even testing the "Deleting a service instance that has a service binding" scenario). Can we just remove the bits to do with bindings? The actual test cases seem related to deprovisioning only.

**Comment by leonwanghui** [comment] 2018-07-30 09:17
Can you take a look at this PR #41 ? It's one proposed solution from my side.

**Closed** 2018-11-06 06:12 UTC
